apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwt-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jwt-app
  template:
    metadata:
      labels:
        app: jwt-app
    spec:
      containers:
        - name: jwt
          image: hanshal101/jwt
          env:
            - name: MONGODB_URI
              value: "mongodb://mongodb-service:27017/"
            - name: JWT_TOKEN
              value: "SECReT"
            - name: IP
              value: "192.168.18.108"
          ports:
            - containerPort: 9876